version: '3.8'
services:
  baggu-database-test:
    container_name: baggu-database-test
    build:
      dockerfile: Dockerfile
      context: ./database
    environment:
      - MARIADB_DATABASE=baggu
      - MARIADB_ROOT_PASSWORD=A708
    volumes:
      - ./database/config:/etc/mysql/conf.d
    ports:
      - "3307:3306"
    restart: always
  baggu-redis-test:
    container_name: baggu-redis-test
    build:
      dockerfile: Dockerfile
      context: ./redis
    ports:
      - "6380:6379"
    restart: always
  baggu-elasticsearch-test:
    container_name: baggu-elasticsearch-test
    deploy:
      resources:
        limits:
          memory: 3G
    environment:
      #      - xpack.license.self_generated.type= trial
      #     - xpack.security.enabled= true
      #      - xpack.monitoring.collection.enabled true
      - node.name= single-node
      - cluster.name= baggutest
      - discovery.type= single-node
      - ELASTIC_PASSWORD= basicpassword
    ports:
      - 9201:9200
    build:
      dockerfile: Dockerfile
      context: ./elasticsearch
      args:
        ELK_VERSION: 7.15.2
    restart: always
  baggu-backend-test:
    container_name: baggu-backend-test
    build:
      dockerfile: Dockerfile-test
      context: ./backend
    environment:
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=A708
      - SPRING_DATASOURCE_URL=jdbc:mariadb://baggu-database-test:3306/baggu
    ports:
      - "8888:9999"
    depends_on:
      - baggu-database-test
    restart: always
  baggu-frontend-test:
    container_name: baggu-frontend-test
    build:
      dockerfile: Dockerfile-test
      context: ./frontend
    ports:
      - "3001:3000"
    restart: always

